version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - app-network

  kafka-setup:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka-setup
    depends_on:
      - kafka
    command: >
      bash -c "
        echo 'Waiting for Kafka to be available...'
        cub kafka-ready -b kafka:9092 1 30
        echo 'Creating topic: reddit_posts_from_r_adidas_may1_6'
        kafka-topics --create --topic reddit_posts_from_r_adidas_may1_6 --bootstrap-server kafka:9092
        echo 'Topic creation completed'
      "
    networks:
      - app-network

  spark-master:
    image: bitnami/spark:3.5.5
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./app:/app
      - ./spark_output:/spark_output
      - ./newcheckpoints:/newcheckpoints
    networks:
      - app-network

  spark-worker:
    image: bitnami/spark:3.5.5
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./app:/app
      - ./spark_output:/spark_output
      - ./newcheckpoints:/newcheckpoints
    networks:
      - app-network

  spark-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-app
    depends_on:
      - spark-master
      - spark-worker
      - kafka
      - kafka-setup
    volumes:
      - ./app:/app
      - ./spark_output:/spark_output
      - ./newcheckpoints:/newcheckpoints
    command: |
      bash -c "
        echo 'Waiting for Kafka to be ready...'
        sleep 20
        echo 'Submitting Spark application...'
        cd /app && ls -la
        /opt/bitnami/spark/bin/spark-submit --master spark://spark-master:7077 --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,com.mysql:mysql-connector-j:8.2.0 --conf spark.jars.ivy=/tmp/.ivy /app/reddit_sentiment.py
      "
    networks:
      - app-network

  producer-app:
    build:
      context: .
      dockerfile: /app/producer/Dockerfile
    container_name: kafka-topic-producer
    depends_on:
      - kafka-setup
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
